### ISSUE TITLE
issue in score_task.py

### ISSUE THREAD

**Issue by SachinSaj** [n-hossain/semeval-2020-task-7-humicroedit#1]
In score_task1.py you have used dev.csv, in that meanGrade column is used for further code. But, in dev.py there is no such column is there. Kindly help me how to proceed with it.

**Comment by n-hossain** [comment]
Treat `score_task1.py` as a template evaluation script. The `meanGrade` column contains the ground truth grades, which for the dev set wont be released until the trial period for the task ends (around Dec 3, 2019). To evaluate your model output, submit the csv containing predictions for the test data in `Codalab` &#8594; `Participate` &#8594; [Submit / View Results](https://competitions.codalab.org/competitions/20970#participate-submit_results) (see template output csv in `output_dev_baseline/` folder).
