### ISSUE TITLE
can not submit result

### ISSUE THREAD

**Issue by umanetz** [n-hossain/semeval-2020-task-7-humicroedit#2]
When submit baseline .csv file get message 'invalid file type (text / csv)'. 
How to solve it?

**Comment by n-hossain** [comment]
We have provided submission templates for both tasks in [here](https://github.com/n-hossain/semeval-2020-task-7-humicroedit/blob/master/output_dev_baseline/). Make sure you submit task-1-output.csv baseline for task-1, and task-2-output.csv for task-2 in Codalab.

If the above does not solve your problem, can you provide more details as to how lines in your files look like, and which task are you submitting for in Codalab?

**Comment by umanetz** [comment]
I try to submit task-1-output.csv baseline file to Development-Task-1.

**Comment by n-hossain** [comment]
I see. You have to put the csv in a zip file, and then submit the zip. If you read the [Evaluation](https://competitions.codalab.org/competitions/20970#learn_the_details-evaluation) section of our Codalab page, it says "The file uploaded for evaluation must be a zip file containing a csv file called "task-1-output.csv"
