### ISSUE TITLE
Bug in baseline_task_2.py

### ISSUE THREAD

**Issue by mdocekal** [n-hossain/semeval-2020-task-7-humicroedit#3]
Hello,
I believe that there is a bug in baseline_task_2.py on line:
`pred = np.argmax(train['label'].value_counts())`
The argmax returns the index not the value, so there will be problem when the series (as in my case) looks like this:

1    4198
2    4184
0     999
Name: label, dtype: int64

I think that the candidate for bug fix could be:
`pred = train['label'].mode()[0]`

**Comment by n-hossain** [comment]
Thanks for the query. Both work ok for me, the argmax returns the value for my case, and my series looks exactly like yours.
