### ISSUE TITLE
"ID mismatch between ground truth and pred"

### ISSUE THREAD

**Issue by Vyomaudi** [n-hossain/semeval-2020-task-7-humicroedit#4]
I tried subumitting my pred(of dev.csv) task-1-output.csv with task-2-output.csv in a zip file but got this error.
Just to check, then i tried to submit your sample outputfiles in a zip. Still i got this error. Can you please guide me.

**Comment by n-hossain** [comment]
Are you submitting the dev results (included as baseline in this repository) in the Post-Evaluation phase? Note that now you can only submit to the Post-Evaluation phase, which requires the test outputs, not the dev outputs for which we have provided the baselines in this repository.

For each task, your submission should include 1 csv in a zip. E.g. for Task 1 submission, go [here](https://competitions.codalab.org/competitions/20970) -> Participate -> Submit / View Results -> Post-Evaluation-Task-1. Then submit a zip file containing task-1-output.csv only which contains predictions for the test set (and includes the test IDs)
